# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Naweel Anwer
email: naweel.a1496@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://naweel1496.github.io" # the base hostname & protocol for your site
twitter_username: naweel_anwer
github_username:  naweel1496

permalink:  none

# Build settings
markdown: kramdown

# /:categories/:title.html
permalink: none

# URLS
link_to:
  facebook:        https://www.facebook.com/nabeel.A1496
  github:          https://github.com/naweel1496
  twitter:         https://twitter.com/naweel_anwer
  linkedin:        https://www.linkedin.com/in/naweel1496/
  github_profile_pic: https://avatars0.githubusercontent.com/u/16776409?v=3&u=229e157816bb7facefa101872d86981092ac680e&s=400
